export default {
    EVENT_SYNC_DEVICES_REQUEST: 'EVENT_SYNC_DEVICES_REQUEST',
    EVENT_SYNC_DEVICES_RESPONSE: 'EVENT_SYNC_DEVICES_RESPONSE',
    EVENT_DEVICE_SELECTED: 'EVENT_DEVICE_SELECTED',
    EVENT_LOGCAT_READY: 'EVENT_LOGCAT_READY',
    EVENT_LOGCAT_SENDING: 'EVENT_LOGCAT_SENDING',
};